Agrega edición de registros en indexer.py
JCMiguel/repository-reviewer pull request #22
Opened 2023-06-16 20:51 UTC by JCMiguel

Agregué la función de edición de fichas que había quedado pendiente.

También ajusté el formato de guardado del csv, la columna de índice me estaba rompiendo la lógica del código.

2023-06-17 18:13 UTC, bassimat reviewed
Hice una revisión de los cambios muy por encima. Luego lo voy a bajar y probar distintos escenarios. Así que, de momento, continua en pendiente la revisión.

2023-06-17 18:18 UTC, bassimat commented on indexer.py
>          if input_a_boolean("¿Está seguro que desea editar esta ficha?") == True:
Me pareció muy interesante como planteaste las interacciones en pantalla. Pero algo que se me ocurrió en esta revisión es que al estar centralizado de esta forma, cuando la app tenga un intefaz gráfica, seguro sería más sencilla la integración. Quizas también ayude para el autocompletado. No sé: lo digo por decir, pero ya lo veremos..

2023-06-24 18:29 UTC, bassimat reviewed
Tengo unos comentarios sobre algunas cosas que no llegué a ver en la revisión anterior del indexer.

- En el modo *get* pide un filename pero no lo usa. Usaría ese parámetro (que pasaría a opcional) para listar un artículo en particular. Si no se utiliza entonces si que liste todos los artículos fichados, como está haciendo ahora.
- En modo *save* hay un comando opcional *--to* que tampoco interviene. Es para fichar en otro archivo de fichas? Este no lo entiendo.

2023-06-25 20:55 UTC, JCMiguel commented
> Tengo unos comentarios sobre algunas cosas que no llegué a ver en la revisión anterior del indexer.
> 
> * En el modo _get_ pide un filename pero no lo usa. Usaría ese parámetro (que pasaría a opcional) para listar un artículo en particular. Si no se utiliza entonces si que liste todos los artículos fichados, como está haciendo ahora.
> * En modo _save_ hay un comando opcional _--to_ que tampoco interviene. Es para fichar en otro archivo de fichas? Este no lo entiendo.

@bassimat Estuve revisando esto. El filename me había quedado como deuda técnica, el método get solo listaba todas las fichas existentes. Tomé tu comentario e implementé una búsqueda medio rudimentaria basada en el número de ficha o el nombre de archivo. En cuanto al parámetro --to, lo comenté porque no recuerdo por qué lo puse.

2023-06-26 23:12 UTC, bassimat requested changes

2023-06-26 23:12 UTC, bassimat commented on indexer.py
> +            new_dict = index_an_article()
Estuve probando y creo que hay un defecto a nivel usabilidad. Te comento a ver que te parece:
Opino que la edición no debería ser ingresar todo nuevamente, sino modificar campos en particular

En ese sentido, se me ocurren 3 alternativas (en orden de preferencia) que luego podemos conversar:
1- En caso de no ingresar un valor de entrada, dejar ese ítem como estaba y continuar la edición con los siguientes
2- Poder indicar un ítem opcional en el método index_an_article( ) para modificar solo ese ítem.
3- Dejarlo así como está, aunque creo que alguna de las alternativas anteriores vendría bien para el autocompletado del issue #14

2023-06-26 23:26 UTC, JCMiguel commented on indexer.py
> +            new_dict = index_an_article()
Creemos un issue para encararlo más adelante.

2023-06-26 23:27 UTC, bassimat commented on indexer.py
> +            new_dict = index_an_article()
Vamos a transformar este pedido de cambio en un nuevo issue para encarar en el 2do milestone.

2023-06-26 23:27 UTC, bassimat approved these changes
Costó pero salió. Todo en orden y aprobado

2023-06-26 23:27 UTC, merged